/home2/y2021/k2110261/.conda/envs/tensorflow/lib/python3.13/site-packages/torch/cuda/__init__.py:129: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 11000). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:108.)
  return torch._C._cuda_getDeviceCount() > 0
[*********************100%***********************]  1 of 1 completed
(2776,)
(2776,)
(2776,)
Date
2012-05-18 00:00:00+00:00     18.373453
2012-05-21 00:00:00+00:00     18.357677
2012-05-22 00:00:00+00:00     18.341911
2012-05-23 00:00:00+00:00     18.326157
2012-05-24 00:00:00+00:00     18.310413
                                ...
2023-05-24 00:00:00+00:00    161.422822
2023-05-25 00:00:00+00:00    161.480456
2023-05-26 00:00:00+00:00    161.538087
2023-05-30 00:00:00+00:00    161.595714
2023-05-31 00:00:00+00:00    161.653338
Name: trend, Length: 2776, dtype: float64
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
Traceback (most recent call last):
  File "/data/student/k2110261/Multi-iTransformer/optunademo.py", line 64, in <module>
    combined_df_trend = pd.DataFrame(dataframes_trend)
  File "/home2/y2021/k2110261/.conda/envs/tensorflow/lib/python3.13/site-packages/pandas/core/frame.py", line 778, in __init__
    mgr = dict_to_mgr(data, index, columns, dtype=dtype, copy=copy, typ=manager)
  File "/home2/y2021/k2110261/.conda/envs/tensorflow/lib/python3.13/site-packages/pandas/core/internals/construction.py", line 503, in dict_to_mgr
    return arrays_to_mgr(arrays, columns, index, dtype=dtype, typ=typ, consolidate=copy)
  File "/home2/y2021/k2110261/.conda/envs/tensorflow/lib/python3.13/site-packages/pandas/core/internals/construction.py", line 119, in arrays_to_mgr
    arrays, refs = _homogenize(arrays, index, dtype)
                   ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "/home2/y2021/k2110261/.conda/envs/tensorflow/lib/python3.13/site-packages/pandas/core/internals/construction.py", line 629, in _homogenize
    val = sanitize_array(val, index, dtype=dtype, copy=False)
  File "/home2/y2021/k2110261/.conda/envs/tensorflow/lib/python3.13/site-packages/pandas/core/construction.py", line 633, in sanitize_array
    return sanitize_array(
        data,
    ...<3 lines>...
        allow_2d=allow_2d,
    )
  File "/home2/y2021/k2110261/.conda/envs/tensorflow/lib/python3.13/site-packages/pandas/core/construction.py", line 659, in sanitize_array
    subarr = _sanitize_ndim(subarr, data, dtype, index, allow_2d=allow_2d)
  File "/home2/y2021/k2110261/.conda/envs/tensorflow/lib/python3.13/site-packages/pandas/core/construction.py", line 718, in _sanitize_ndim
    raise ValueError(
        f"Data must be 1-dimensional, got ndarray of shape {data.shape} instead"
    )
ValueError: Data must be 1-dimensional, got ndarray of shape (2776, 1) instead
