/home2/y2021/k2110261/.conda/envs/tensorflow/lib/python3.13/site-packages/torch/cuda/__init__.py:129: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 11000). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:108.)
  return torch._C._cuda_getDeviceCount() > 0
[*********************100%***********************]  1 of 1 completed
(2776,)
(2776,)
(2776,)
{'AAPL': Date
2012-05-18 00:00:00+00:00     18.373451
2012-05-21 00:00:00+00:00     18.357675
2012-05-22 00:00:00+00:00     18.341910
2012-05-23 00:00:00+00:00     18.326155
2012-05-24 00:00:00+00:00     18.310412
                                ...
2023-05-24 00:00:00+00:00    161.422848
2023-05-25 00:00:00+00:00    161.480483
2023-05-26 00:00:00+00:00    161.538114
2023-05-30 00:00:00+00:00    161.595741
2023-05-31 00:00:00+00:00    161.653365
Name: trend, Length: 2776, dtype: float64}
{'AAPL': Date
2012-05-18 00:00:00+00:00    -2.037160
2012-05-21 00:00:00+00:00    -1.339883
2012-05-22 00:00:00+00:00    -1.369425
2012-05-23 00:00:00+00:00    -1.131666
2012-05-24 00:00:00+00:00    -1.129779
                               ...
2023-05-24 00:00:00+00:00    -6.710167
2023-05-25 00:00:00+00:00   -10.178088
2023-05-26 00:00:00+00:00   -10.052280
2023-05-30 00:00:00+00:00    -6.308023
2023-05-31 00:00:00+00:00    -3.033107
Name: season, Length: 2776, dtype: float64}
[*********************100%***********************]  1 of 1 completed
GOOGL
[*********************100%***********************]  1 of 1 completed
META
[*********************100%***********************]  1 of 1 completed
AMZN
[*********************100%***********************]  1 of 1 completed
MSFT
[32m[I 2024-11-01 22:02:26,017][0m A new study created in memory with name: no-name-48f42f6d-7e24-4f02-b094-a3bcde0397f3[0m
/data/student/k2110261/Multi-iTransformer/optunademo.py:91: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-6, 1e-3)
[33m[W 2024-11-01 22:02:26,232][0m Trial 0 failed with parameters: {'learning_rate': 3.799341842397698e-05, 'batch_size': 174, 'step_size': 8, 'gamma': 0.8398195884105567, 'depth': 4, 'dim': 179} because of the following error: UnboundLocalError("cannot access local variable 'model_trend' where it is not associated with a value").[0m
Traceback (most recent call last):
  File "/home2/y2021/k2110261/.conda/envs/tensorflow/lib/python3.13/site-packages/optuna/study/_optimize.py", line 197, in _run_trial
    value_or_values = func(trial)
  File "/data/student/k2110261/Multi-iTransformer/optunademo.py", line 134, in <lambda>
    study_trend.optimize(lambda trial: objective(trial, "trend"), n_trials=1)
                                       ~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/data/student/k2110261/Multi-iTransformer/optunademo.py", line 121, in objective
    model_trend, train_data_trend, valid_data_trend, optimizer_trend, criterion, scheduler_trend, best_params_trend['batch_size'], observation_period_num)
    ^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'model_trend' where it is not associated with a value
[33m[W 2024-11-01 22:02:26,238][0m Trial 0 failed with value None.[0m
Traceback (most recent call last):
  File "/data/student/k2110261/Multi-iTransformer/optunademo.py", line 134, in <module>
    study_trend.optimize(lambda trial: objective(trial, "trend"), n_trials=1)
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home2/y2021/k2110261/.conda/envs/tensorflow/lib/python3.13/site-packages/optuna/study/study.py", line 475, in optimize
    _optimize(
    ~~~~~~~~~^
        study=self,
        ^^^^^^^^^^^
    ...<7 lines>...
        show_progress_bar=show_progress_bar,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home2/y2021/k2110261/.conda/envs/tensorflow/lib/python3.13/site-packages/optuna/study/_optimize.py", line 63, in _optimize
    _optimize_sequential(
    ~~~~~~~~~~~~~~~~~~~~^
        study,
        ^^^^^^
    ...<8 lines>...
        progress_bar=progress_bar,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home2/y2021/k2110261/.conda/envs/tensorflow/lib/python3.13/site-packages/optuna/study/_optimize.py", line 160, in _optimize_sequential
    frozen_trial = _run_trial(study, func, catch)
  File "/home2/y2021/k2110261/.conda/envs/tensorflow/lib/python3.13/site-packages/optuna/study/_optimize.py", line 248, in _run_trial
    raise func_err
  File "/home2/y2021/k2110261/.conda/envs/tensorflow/lib/python3.13/site-packages/optuna/study/_optimize.py", line 197, in _run_trial
    value_or_values = func(trial)
  File "/data/student/k2110261/Multi-iTransformer/optunademo.py", line 134, in <lambda>
    study_trend.optimize(lambda trial: objective(trial, "trend"), n_trials=1)
                                       ~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/data/student/k2110261/Multi-iTransformer/optunademo.py", line 121, in objective
    model_trend, train_data_trend, valid_data_trend, optimizer_trend, criterion, scheduler_trend, best_params_trend['batch_size'], observation_period_num)
    ^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'model_trend' where it is not associated with a value
